global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX Exporters (Updated ports)
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: 
          - 'kafka-jmx-exporter1:9101'
          - 'kafka-jmx-exporter2:9102'
          - 'kafka-jmx-exporter3:9103'
    scrape_interval: 30s
    metrics_path: /metrics

  # Application metrics
  - job_name: 'ruuvitag-adapter'
    static_configs:
      - targets: ['ruuvitag-adapter:8002']
    scrape_interval: 15s

  - job_name: 'kafka-consumer'
    static_configs:
      - targets: ['kafka-consumer:8001']
    scrape_interval: 15s

  - job_name: 'timescaledb-sink'
    static_configs:
      - targets: ['timescaledb-sink:8003']
    scrape_interval: 15s

  # Infrastructure metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'mosquitto-exporter'
    static_configs:
      - targets: ['mosquitto-exporter:9234']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s